apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: smartvillage
  namespace: sso
  labels:
    app: sso
spec:
  realmSelector:
     matchLabels:
      app: sso
      realm: SMARTVILLAGE
  client:
    clientId: smartvillage
    standardFlowEnabled: true
    serviceAccountsEnabled: true
    authorizationServicesEnabled: true
    protocol: openid-connect
    redirectUris:
      - http://localhost:12080/logout
      - http://localhost:12080/callback
