apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: sso-group-sync
  namespace: group-sync-operator
spec:
  providers:
    - name: sso
      keycloak:
        loginRealm: master
        realm: SMARTVILLAGE
        credentialsSecret:
          name: sso-group-sync
          namespace: group-sync-operator
        url: https://keycloak-sso.apps-crc.testing
        ca:
          kind: ConfigMap
          name: sso-ca-config-map
          namespace: group-sync-operator
          key: ca.crt
