apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  namespace: smart-village-view
  name: smartvillage-traffic-light-controller-sumo
spec:
  selector:
    app: smartvillage-traffic-light-controller-sumo
  replicas: 1
  template:
    metadata:
      labels:
        app: smartvillage-traffic-light-controller-sumo
    spec:
      containers:
        - resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 500Mi
          readinessProbe:
            httpGet:
              path: /
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 20
          terminationMessagePath: /dev/termination-log
          name: smartvillage-traffic-light-controller-sumo
          livenessProbe:
            httpGet:
              path: /
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 20
          env:
            - name: KAFKA_BROKERS
              value: >-
                smartvillage-kafka-kafka-brokers.smart-village-view.svc.cluster.local:9092
            - name: KAFKA_GROUP
              value: smartvillage-kafka-group
            - name: KAFKA_TOPIC_SUMO_RUN
              value: smartvillage-sumo-run
            - name: KAFKA_TOPIC_SUMO_RUN_REPORT
              value: smartvillage-sumo-run-report
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
      imagePullSecrets: []
  strategy:
    type: Rolling
    resources: {}
    activeDeadlineSeconds: 21600
    rollingParams:
      timeoutSeconds: 600
      updatePeriodSeconds: 1
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - smartvillage-traffic-light-controller-sumo
        from:
          kind: ImageStreamTag
          name: 'smartvillage-traffic-light-controller-sumo:computate-api'
          namespace: smart-village-view
    - type: ConfigChange
  paused: false
