DROP TABLE SiteUser CASCADE;
DROP TABLE SimulationReport CASCADE;
DROP TABLE SmartTrafficLight CASCADE;
DROP TABLE TrafficFlowObserved CASCADE;
DROP TABLE TrafficSimulation CASCADE;
DROP TABLE CrowdFlowObserved CASCADE;
