apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
  name: betydb-helm
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/computate-org/bety-helm.git
    targetRevision: HEAD
    path: .
    helm:
      releaseName: betydb
      parameters:
        - name: postgresql.enabled
          value: "false"
        - name: postgresql.fullnameOverride
          value: "pecan-postgresql"
        - name: postgresql.serviceAccount.enabled
          value: "true"
        - name: postgresql.postgresqlHost
          value: "pecan-postgresql.pecan.svc.cluster.local"
        - name: serviceAccount.enabled
          value: "true"
        - name: serviceAccount.name
          value: "pecan-betydb"
        - name: externalSecret
          value: "false"
        - name: nameOverride
          value: "pecan"
        - name: fullnameOverride
          value: "pecan-betydb"
  destination:
    namespace: pecan
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      # resources that no longer exist get deleted on sync
      prune: true
      # sync will be attempted again on failure after self heal timeout (5 seconds by default)
      selfHeal: true
