apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: serverless
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/computate-org/smartvillage-platform.git
    targetRevision: HEAD
    path: openshift/kustomize/bundles/custom-metrics-autoscaler/app
  destination:
    namespace: pecan
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      # resources that no longer exist get deleted on sync
      prune: true
      # sync will be attempted again on failure after self heal timeout (5 seconds by default)
      selfHeal: true
