apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: smartvillage-kafka
  namespace: smart-village-view
  labels:
    strimzi.io/cluster: smartvillage-kafka
spec:
  authentication:
    type: tls
  authorization:
    acls:
      - host: '*'
        operation: All
        resource:
          name: smartvillage-
          patternType: prefix
          type: topic
        type: allow
      - host: '*'
        operation: All
        resource:
          name: smartvillage-
          patternType: prefix
          type: group
        type: allow
    type: simple
