---
apiVersion: build.openshift.io/v1
kind: BuildConfig
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: '{{ SITE_NAME }}:latest'
  postCommit: {}
  resources:
    limits:
      memory: 1.5Gi
    requests:
      memory: 1.5Gi
  runPolicy: Serial
  source:
    git:
      uri: '{{ SITE_REPO_HTTPS }}'
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'java:latest'
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
    - imageChange:
      type: ImageChange
    - type: ConfigChange
