apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: betydb-secret-key
  namespace: pecan
spec:
  authentication: 
    path: kubernetes
    role: secret-writer
  connection:
    address: 'http://vault.vault.svc.cluster.local:8200'
  path: pecan/kv
  secretKey: secretKey
  secretFormat:
    passwordPolicyName: simple-password-policy-15
